### ISSUE TITLE
Composer: package fgrosse/phpasn1 is abandoned, you should avoid using it

### ISSUE THREAD

**Issue by Sebastix** [swentel/nostr-php#20]
https://packagist.org/packages/fgrosse/phpasn1

This library is no longer actively maintained.

**Comment by swentel** [comment]
public-square/phpecc has a requirement on it, and there's an issue there already. https://github.com/phpecc/phpecc/issues/285

As far as I can see,  SchnorrSignature (because that why we depend on phpecc) has no uses from that package at all, so it's not a problem at all at this point. Unless we can find a replacement package for that functionality (without forking it ourselves, not my intention), we can ignore that warning.

If we could add something to our code to suppress that warning, that would be even better, but I don't think composer has that (unless I'm looking wrong).

**Comment by swentel** [comment]
subscribed myself on the other issue - phpecc is relatively unmaintained too, but we need that. Again, no real big issues here.
